### ISSUE TITLE
Can this work with .less files?

### ISSUE THREAD

**Issue by Gruntfuggly** [csstree/atom-plugin#1]
This is a really nice plugin! Could it work with less files too?

**Comment by smelukov** [comment]
Thanks for feedback.
CSSTree is only for pure CSS syntax.
That's why it can't work with preprocessors.
But we're working on some improvements for using csstree validator inside a gulp chain: `input` -> `less/sass/etc` -> `csstree` -> `some other plugins` -> `output`
But now it's only a draft ;)
