### ISSUE TITLE
Cannot read property 'line' of null

### ISSUE THREAD

**Issue by fogrew** [csstree/atom-plugin#2]
While I'm writing styles, the plugin shows an error
> Cannot read property 'line' of null

![CSSTree error](http://grlv.ru/i/6u2qd.png)

I wrote
```css
max-height: ;
```
Then, when I enter the value, the error disappears. So what happens with all the unfinished values.

It would be nice if this error does not appear until I enter at least some non-empty value. Thanks!

**Comment by lahmatiy** [comment]
Thank you for issue!

The message `Cannot read property 'line' of null` says about internal error and should be fixed. @smelukov could you investegate the problem?

Nevertheless, currently `csstree` doesn't support for tollerant parsing. So some kind of error might to be displayed when CSS is not valid. At the same time, your example `max-height: ;` is a "valid" CSS and no warning should be displayed.

**Comment by smelukov** [comment]
@lahmatiy, @Gurylev thanks! I'll investigate it

**Comment by smelukov** [comment]
Fixed in release v0.1.0
Please update the plugin
